# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: jmccauli@gmail.com
author_name: Justin McCauliffe
cloud_provider: none
preset_name: production
project_name: staking-frontend

