# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.2
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: jmccauli@gmail.com
author_name: Justin McCauliffe
contract_name: staking
preset_name: production
project_name: staking-contracts

