# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: jmccauli@gmail.com
author_name: Justin McCauliffe
cloud_provider: none
contract_name: staking
preset_name: production
project_name: staking

